name: Deploy

on: push

jobs:

    build:
      runs-on: ${{ matrix.os }}

      strategy:
          matrix:
              os: [ ubuntu-latest, windows-latest ]
              node: [ 18, 20 ]

      services:
          redis:
              image: redis
              ports:
                  - 6379:6379

      steps:
        - name: Checkout
          uses: actions/checkout@v4
      
        - name: Print variable
          run: echo "${{ secrets.TOKEN_SECRET }}"

        - name: setup
          uses: actions/setup-node@v4
          with:
              node-version: ${{ matix.node }}

        - name: Install redis cli
          run: sudo apt-get update -y && sudo apt-get install redis-tools -y

        - name: Test Redis
          run: redis-cli -h localhost -p 6379 ping 

        - name: Instalar dependencias
          run: npm install

        - name: testing
          run: npm run test

        - name: Build page
          run: npm run build

        - name: upload Artifact
          if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == '18' }}
          uses: actions/upload-pages-artifact@v3
          with:
              path: public/
          
    deploy:
        if: ${{ always() }}
        needs: build

        permissions:
            pages: write
            id-token: write

        environment:
            name: github-pages
            url: ${{ steps.deployment-pages.outputs.page_url }}

        runs-on: ubuntu-latest

        steps:

            - name: DeployEcho
              run: echo "Deploy...application"

            - name: Deploy
              id: deployment-pages
              uses: actions/deploy-pages@v4
              
              
              

        


